### ISSUE TITLE
Welcome to day4!

### ISSUE THREAD

**Issue by naotakke** [GuildWorks/titech-2020#33]
titech-2020 Day4 のワークショップ実施のため、皆さんの GitHub アカウントを教えてほしいです！

↓ からなんでも良いのでコメントを書いてください！
![image](https://user-images.githubusercontent.com/67668304/100446197-b5c88100-30f1-11eb-9fb9-89fd23d23e14.png)

**Comment by naotawool** [comment]
Hello @naotakke !!

**Comment by iwannabebolt** [comment]
こんにちは！下山達大です！

**Comment by bigglasses93** [comment]
hello @naotakke

**Comment by ShoFurubayashi** [comment]
よろしくお願いします

**Comment by Elain26** [comment]
Hello! This is HUANG Yilin.

**Comment by hase7039** [comment]
よろしくおねがいします

**Comment by Kirihara-Yuji** [comment]
こんにちは桐原です．

**Comment by kokarimashika** [comment]
よろしくお願いします！

**Comment by ong-ekken** [comment]
エッケンです、よろしくお願いします

**Comment by meck080808** [comment]
三宅ですよろしくお願いいたします

**Comment by Tadashunsuke** [comment]
多田駿介

**Comment by Hyuga0723** [comment]
鬼滅面白かった

**Comment by jun116** [comment]
![image](https://user-images.githubusercontent.com/691689/100493829-67ad8f00-317e-11eb-9093-6c57a45fa2a1.png)

**Comment by Takuyuki516** [comment]
丸山です、お願いします

**Comment by Takaki-imaizumi** [comment]
今泉です　よろしくお願いします！

**Comment by kimumusan** [comment]
おねがいします。

**Comment by leviet08** [comment]
こんにちは！

**Comment by yamadai0928** [comment]
遅くなりました山下です。よろしくお願いします。

**Comment by disha2695** [comment]
Hello
